vgteam/libhandlegraph

src/include/handlegraph/handle_graph.hpp

Reversing edges were not accounted for previously

fix bug in for_each_edge in handle_graph.hpp

---

src/handle.cpp
src/include/handlegraph/deletable_handle_graph.hpp
src/include/handlegraph/mutable_handle_graph.hpp
src/include/handlegraph/mutable_path_deletable_handle_graph.hpp
src/include/handlegraph/mutable_path_handle_graph.hpp
src/include/handlegraph/mutable_path_mutable_handle_graph.hpp
src/include/handlegraph/path_handle_graph.hpp
src/include/handlegraph/types.hpp
src/include/handlegraph/util.hpp

This PR resolves all of our oustanding issues! (https://github.com/vgteam/libhandlegraph/issues/2, https://github.com/vgteam/libhandlegraph/issues/3, https://github.com/vgteam/libhandlegraph/issues/4)
Specifically, the changes included are:
- Removed `swap_handles` and `apply_ordering`.
- Make `MutablePathDeletableHandleGraph` actually inherit from `MutablePathMutableHandleGraph`.
- Changed documentation to indicate that `MutablePathDeletableHandleGraph`s are expected to delete paths when calling `clear()`.
- Changed "occurrence" terminology to "step".
- New methods added to `PathHandleGraph` to check path circularity and in `MutablePathHandleGraph` to set path circularity.
- Added a past-the-last iterator concept for `step_handle_t`, to be returned by `path_end()` and by …

Path improvification

---

src/include/handlegraph/mutable_path_handle_graph.hpp

Adding two functions to the interface for mutable paths:
- Prepend steps to a path
- Rewrite a segment of a path
Updates in VG to implement the interface to follow.

Add more edits to the mutable path interface

---

src/include/handlegraph/handle_graph.hpp
src/include/handlegraph/path_handle_graph.hpp

This is my proposal to address the concerns I noted in the discussion on https://github.com/vgteam/libhandlegraph/pull/13. Changes include:
- Renamed methods to use a terminology to refer to the endpoints of paths that I think is more internally consistent as well as more consistent with the STL (`path_begin` / `path_end` / `path_rbegin` / `path_rend`)
- Reverted the stock implementation of `for_each_step_in_path`. I'm willing to be convinced otherwise, but it really looked to me that the new edits were broken and would result in an infinite loop on circular paths.
- Updated the documentation to be (in my estimation) more unambiguous and specific.
I think the confusion we're having might be partly due to differences of opinion on what the iteration should be doing on circular paths. I …

Proposal for modified interface to do reverse iteration on paths

---

src/include/handlegraph/handle_graph.hpp

Here's my proposal for a serialization/deserialization scheme.
I put it in a separate class for now, but I think the right way to do this is with one of @adamnovak 's HandleGraph traits. As such, I'm not going to bother working it into the class hierarchy. I also considered putting these methods in the base `HandleGraph`, but there are things like overlays that we don't care to have serialization methods for.
One thing I wish I could do here is to include a virtual constructor like:
```
class HandleGraph {
virtual HandleGraph(std::istream& in) = 0;
};
```
Anyway, turns out virtual constructors prohibited in C++. I opted to have a `deserialize` method instead, but I don't love that this more or less requires you to first construct an empty graph and then deserialize in two distinct steps.

Proposal for a serialization interface

---

src/include/handlegraph/handle_graph.hpp

Travis caught this in its own cryptic way ([weird crashes only on mac/gcc=1](https://travis-ci.org/vgteam/vg/jobs/583250672)), which turned out to come from using a `unique_ptr<VectorizableHandleGraph>`.

Add missing virtual destructors

---

src/include/handlegraph/handle_graph.hpp
src/include/handlegraph/mutable_handle_graph.hpp

@jeizenga this is what I was talking about doing to make it so we can have a generic from-GFA loader algorithm that works on models (just odgi for now) that need to know the minimum node id in order to build an efficient in-memory model.
What do you think? Is there a better way to do this? I can also just hack this into odgi and we can give it custom loading code for our tests. That might be better.

set a node id increment hint

---

src/include/handlegraph/mutable_handle_graph.hpp

This is required to handlify `vg ids -j`

Add increment_node_ids method to mutable handle graph

---

src/handle.cpp
src/include/handlegraph/handle_graph.hpp

Some implementations (vg, xg) internally know how many edges and/or bases are in the graph. This adds methods that can be used to ask those questions, with default implementations that do linear scans through the basic handle API.

Add overridable methods for total edges and total length

---

src/handle.cpp
src/include/handlegraph/mutable_handle_graph.hpp

I need this more general interface to implement vg ids -s against a HashGraph instead of a vg::VG.

Add an operation to reassign IDs, and a default implementation for ID increment.

---

src/include/handlegraph/expanding_overlay_graph.hpp

The libbdsg binding build process doesn't want to deal with includes relative to the current directory.

Use library name in include to not upset Binder

---

src/include/handlegraph/serializable_handle_graph.hpp
src/include/handlegraph/types.hpp

This makes sure to remove non-fixed types like int64_t from the public interface (so Python bindings generated with Binder can be portable) and also adds serialization and deserialization with filenames (so languages that can't work with C++ streams can load and save graphs).

Allow for portable and useful Python bindings

---

CMakeLists.txt

We need this for the libbdsg Python bindings to work out of the box on Mac. They build but don't actually install libhandlegraph.

Set up absolute install_name for Mac

---

src/include/handlegraph/path_handle_graph.hpp

We should only return false from an iteration method if we stop early.

Make for_each_step_in_path return true when done

---

src/include/handlegraph/deletable_handle_graph.hpp
src/include/handlegraph/mutable_handle_graph.hpp

Specify that removing nodes will destroy any paths they are still on, and prohibit users from creating/allow graphs to reject empty nodes.

Tighten semantics

---

src/handle.cpp
src/include/handlegraph/handle_graph.hpp

This also causes VectorizableHandleGraph (via RankedHandleGraph) to actually be a HandleGraph, so you can ask for a VectorizableHandleGraph or RankedHandleGraph if you want to guarantee you have a whole graph with those operations available. This in turn lets you make fewer duplicate overlays.

Add RankedHandleGraph with just a node/handle ordering

---

src/include/handlegraph/path_handle_graph.hpp

This is important for merging with upstream odgi.

allow getting the step count of a handle

---

CMakeLists.txt

This includes some commits libbdsg has been using, as well as making Mac @rpath usage depend on whether er think we're a subdirectory of another project or not.

Make usable from libbdsg for libbdsg Pip installation

---

src/handle.cpp
src/include/handlegraph/deletable_handle_graph.hpp

The semantics are to remove one half of a node from a given offset. It can be accomplished by composing `divide_handle` with `destroy_handle`, but I want to have the option of a more efficient implementation as well.

Add a truncate method with a default implementation to DeletableHandleGraph interface

---

src/handle.cpp
src/include/handlegraph/path_handle_graph.hpp

A new method `get_step_count` for a `handle_t` was added, but implementations weren't added elsewhere. This PR adds a default implementation based on `for_each_step_on_handle` so that things will keep running.

Add a default implementation for handle get_step_count method

---

src/include/handlegraph/trivially_serializable.hpp

I eventually gave up on not overriding this for the PackedGraph memory mapping, but forgot to PR it until just now.

De-finalize TriviallySerializable

---

src/chop.cpp

We were not appropriately handling runs of nodes that had self-loops. The new unchopped node handles were being used to remove edges on the chopped nodes. This PR pushes that logic into the `destroy_handle` method, which should handle edges already anyway.

Fix bug in unchop

---

src/include/handlegraph/trivially_serializable.hpp
src/trivially_serializable.cpp

Require serialize-to-byte-range-views instead of a const serialize-to-fd from TriviallySerializable, and provide a default const serialize-to-fd implementation.

Const serialize

---

src/include/handlegraph/types.hpp

Looks like we dropped a `*` here.

Hash net_handle_t values instead of addresses

---

src/chop.cpp
src/include/handlegraph/algorithms/chop.hpp
src/include/handlegraph/mutable_handle_graph.hpp

This adds machinery we need to track nodes through `vg chop`. vg will need this for GFA-space compatibility.

Allow tracking nodes through chop

---

CMakeLists.txt
src/copy_graph.cpp
src/include/handlegraph/mutable_path_handle_graph.hpp
src/include/handlegraph/mutable_path_metadata.hpp
src/include/handlegraph/path_handle_graph.hpp
src/include/handlegraph/path_metadata.hpp
src/mutable_path_metadata.cpp
src/path_metadata.cpp

This will fix #75 by adding a metadata API to let you get e.g. the sample and haplotype of a path, and some methods that are specified to let you obtain path handles for haplotypes.
I had to complicate the search methods a bit from what I proposed in #75, because almost immediately upon trying to use this I started needing to e.g. look up all the haplotypes for a sample, which wasn't supported in the original formulation.

Path metadata API

---

src/count_walks.cpp
src/include/handlegraph/mutable_path_handle_graph.hpp

We could overflow in the final return condition, but we only checked overflow in the DP.

Fix a bug in the overflow detection in count_walks

---

src/path_metadata.cpp

Was getting a weird "reference path can't have haplo block" error when parsing then writing the same path when I noticed this...

add missing else to parse_path_name()

---

src/dijkstra.cpp
src/include/handlegraph/algorithms/dijkstra.hpp

This lets you use `vg::algorithms::dijkstra()` to do a pruned search: instead of stopping when you return false for a node, it will instead just stop exploring from that node, and keep exploring from other nodes.
It also lets you skip the initial visit(s) to the starting node(s), so they can be visited later with shortest paths to them from themselves or other start nodes.

Add more modes to Dijkstra search

---

src/include/handlegraph/serializable.hpp

This one-liner enables us to compile libhandlegraph with GCC 13.1. This update is required so we can actually compile ODGI with this compiler version. See https://github.com/pangenome/odgi/pull/507.

enable GCC v13.1 compilation

---

src/include/handlegraph/path_metadata.hpp
src/path_metadata.cpp

The [PanSN spec](https://github.com/pangenome/PanSN-spec#the-pattern) says the haplotype number has to actually be a number. Right now if it isn't a number, we match our regex but then try to parse the non-number and crash.
This should fix it to not match the regex anymore when it won't be able to be parsed due to not really being a number.

Stop parsing `ARS_UCD12#hap0#6` as PanSN

---

src/path_metadata.cpp

I missed a case in #91 and the full and by-field parsers got out of sync. The full one lost the ability to handle e.g. `GRCh38#chr1`, which is pretty important but wasn't in the vg tests.
This should fix the bug, and I am adding some tests to vg.

Handle full parsing of two-part path names

---

CMakeLists.txt
cmake/libhandlegraphConfig.cmake

Now if you `find_package(libhandlegraph)`, and the `CMAKE_INSTALL_PREFIX` that libhandlegraph installed into is in your `CMAKE_PREFIX_PATH`, you will see `libhandlegraph::handlegraph_static` and `libhandlegraph::handlegraph_shared` targets, and `$libhandlegraph_FOUND` will be true.
If you want to fall back to a bundled libhandlegraph, you can poll that variable and, if it isn't set, add libhandlegraph as a subdirectory and alias is targets into the namespace, and then you can just use the namespaced targets for the rest of the build.

Install a CMake config to enable find_package(libhandlegraph)

---

src/include/handlegraph/mutable_path_handle_graph.hpp
src/mutable_path_handle_graph.cpp

Pretty straightforward. I'm adding this to facilitate a more efficient batch path destroy in `libbdsg`.

Add a batch path destroy function with a default implementation

---

CMakeLists.txt
src/deletable_handle_graph.cpp
src/include/handlegraph/deletable_handle_graph.hpp
src/include/handlegraph/mutable_path_deletable_handle_graph.hpp
src/mutable_path_deletable_handle_graph.cpp

This is part of a larger PR to allow sequences to be hard-masked in VG by internally replacing them with N's.

Add an interface in DeletableHandleGraph to change the sequence
